### ISSUE TITLE
About Training

### ISSUE THREAD

**Issue by Xiaohuangwudi** [abdohelmy/D-3Former#1]
This is a great job

But when I was training CIFAR100, I always had a 2% accuracy rate. I haven't changed any code, please tell me why?

**Comment by abdohelmy** [comment]
Thank you.

It is a rare issue that occurs with NesT, where some random initializations cause the model to diverge to random guess accuracy. This issue only happens during the zeroth phase. Increasing the warm-up epochs to 20 epochs greatly reduces the chance of it happening.
